// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordingOfViolations.Models;

#nullable disable

namespace RecordingOfViolations.Migrations
{
    [DbContext(typeof(ViolationContext))]
    [Migration("20221017223649_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecordingOfViolations.Models.PaymentСheck", b =>
                {
                    b.Property<int>("PaymentСheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentСheckId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViolationId")
                        .HasColumnType("int");

                    b.HasKey("PaymentСheckId");

                    b.ToTable("PaymentСhecks");
                });

            modelBuilder.Entity("RecordingOfViolations.Models.Violation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Offender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Policeman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ViolationId");

                    b.ToTable("Violations");

                    b.HasData(
                        new
                        {
                            ViolationId = 1,
                            Address = "вулиця Інститутська, 22",
                            Date = new DateTime(2022, 10, 10, 1, 36, 48, 904, DateTimeKind.Local).AddTicks(9181),
                            Offender = "Cпівак Олег",
                            Policeman = "Кукурудза Валерій",
                            Price = 1750m,
                            Reason = "Порушення правил користування ременями безпеки або мотошоломами"
                        },
                        new
                        {
                            ViolationId = 2,
                            Address = "Львівське шосе, 38/1",
                            Date = new DateTime(2022, 9, 25, 1, 36, 48, 904, DateTimeKind.Local).AddTicks(9188),
                            Offender = "Ткачук Петро",
                            Policeman = "Щур Сергій",
                            Price = 510m,
                            Reason = "Нетверезий стан"
                        },
                        new
                        {
                            ViolationId = 3,
                            Address = "вулиця Соборна, 11",
                            Date = new DateTime(2022, 10, 16, 1, 36, 48, 904, DateTimeKind.Local).AddTicks(9195),
                            Offender = "Олійник Яна",
                            Policeman = "Щур Сергій",
                            Price = 750m,
                            Reason = "Порушення правил перевезення дітей"
                        },
                        new
                        {
                            ViolationId = 4,
                            Address = "вулиця Трудова, 6А",
                            Date = new DateTime(2022, 10, 4, 1, 36, 48, 904, DateTimeKind.Local).AddTicks(9202),
                            Offender = "Пристувчук Олександр",
                            Policeman = "Кукурудза Валерій",
                            Price = 15000m,
                            Reason = "Порушення правил зупинки маршрутних таксі"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
